### ISSUE TITLE
cmake-c-compiler-identification-fails

### ISSUE THREAD

**Issue by dont7** [SlaterLatiao/RevBugBench#10]
I'm trying "FixReverter Bug Injection",
![image](https://user-images.githubusercontent.com/125136644/218262282-a088a407-a521-4d15-b13c-83cdcea4b286.png)
while running the command marked in blue, an error occurs to "Step 21/52 : RUN cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..".
Here are error messages.
![image](https://user-images.githubusercontent.com/125136644/218262469-9f66629a-4451-4f91-b871-5ecd4ddee70d.png)
Part of the CMakeError.log shows,
![image](https://user-images.githubusercontent.com/125136644/218263467-ae6bde81-4b11-4287-84e0-8e110ddb5434.png)
In that container I did "chmod 777 -R /usr/local/llvm-12",but it still shows "Permission denied" .
As for "Compiling the C compiler identification failed",I've tried https://stackoverflow.com/questions/41589430/cmake-c-compiler-identification-fails, but it doesn't work.

**Comment by dont7** [comment]
however, when I add "RUN chmod -R 777 /usr/local/llvm-12" to Dockerfile,it works.

**Comment by SlaterLatiao** [comment]
Thank you for reaching out regarding FixReverter. I apologize for the inconvenience, but I couldn't replicate the issue. However, I'm glad that you found a solution on your own.
