### ISSUE TITLE
triage binary

### ISSUE THREAD

**Issue by sykweon** [SlaterLatiao/RevBugBench#20]
when the readme and `triage/setup/triage_bin.py` mentions `triage binaries`, is it referring to the normal fuzzing target binary? Or are we expected to build binary under a specific setting?

**Comment by SlaterLatiao** [comment]
The triage binaries are different from fuzzing targets. Please see the "Triage binary images" section in the [README](https://github.com/UTD-FAST-Lab/RevBugBench/blob/main/README.md).

**Comment by sykweon** [comment]
hello,
when I follow the README instruction and make a triage image, the last few lines of output I get are these:
```
 => preparing layers for inline cache                                                                                                                                                         
 => exporting to image                                                                                                                                                                        
 => => exporting layers                                                                                                                                                                       
 => => writing image sha256:862418ddf24a9d0dd2b4027cd7d2877b5eac045e3e3f1b9619de748edde181c3                                                                             
 => => naming to gcr.io/fuzzbench/builders/fr_triage_driver/lcms
```
However, I could not find any new binary built after the make nor in the docker image created. Where can I possibly find the binary? Or is there an additional step I should take to build the binary?

**Comment by SlaterLatiao** [comment]
The triage script will automatically [copy the triage binary to workDir](https://github.com/UTD-FAST-Lab/RevBugBench/blob/main/triage/setup/triage_bin.py#L27). The README is now updated to reflect this info.

**Comment by sykweon** [comment]
I believe the script is copying the binary from `/out/` directory. In my case, `make` command does not create such a directory or binary. So when I run the script, it outputs an error saying no such file or directory found. Should I set OUT environmental variable while running make?

**Comment by SlaterLatiao** [comment]
`$OUT` should be already set by the FuzzBench base image. Have you followed the versions in "fuzzbench" and "benchmarks" sections in the README? The benchmark Dockerfile inherits from a specific [version](https://github.com/UTD-FAST-Lab/RevBugBench/blob/main/benchmarks/lcms/Dockerfile#L17) of the base image. Building the triage image should not complete without `/out`, as [this command](https://github.com/UTD-FAST-Lab/RevBugBench/blob/main/benchmarks/lcms/build.sh#L23C45-L23C45) would fail.

**Comment by sykweon** [comment]
In the original post when I said "normal fuzzing target", I was actually referring to the binary created at [this command](https://github.com/UTD-FAST-Lab/RevBugBench/blob/8e06e14a1f54625a0ec08b01424d05843cb4476a/benchmarks/lcms/build.sh#L23C45-L23C45). I'm a bit confused because seems like you are implying that binary is the triage binary. So does that mean `make -f triage.mk .fr_triage_driver-[benchmark name]-builder` is not meant to build a new binary, but it only builds the docker image?

**Comment by SlaterLatiao** [comment]
In FuzzBench you can find a _coverage_ folder in the `fuzzers` directory. Instead producing a fuzzing target, the _coverage_ builds a binary that produces llvm coverage profile. We use a similar idea for the triage binaries. The make command `make -f triage.mk .fr_triage_driver-lcms-builder` builds the builder image for fuzzer of _fr_triage_driver_ and benchmark of _lcms_. The resulting docker image will have the binary of _lcms_ (cms_transform_fuzzer) built from _fr_triage_driver_, which is the triage binary.

**Comment by sykweon** [comment]
Thank you. One last question to confirm I understood everything accurately, that means we would be using two different binaries to run the fuzzer and run the triage task, right? For example, if I want to test arbitrary fuzzer A, I would build the fuzzbench with revbugbench patch and run the fuzzer target to get the result. Then, I will build another target from `fr_triage_driver` to do the triage task with. 

Am I understanding this correctly?

**Comment by SlaterLatiao** [comment]
Each (fuzzer, benchmark) pair will need a fuzzing target. For triage each benchmark will have a triage binary. So if you have 2 fuzzers and 1 benchmark, 2 fuzzing target binaries and 1 triage binary will be needed. Benchmarks in RevBugBench is designed to be compatible with FuzzBench benchmarks. Building and fuzzing the fuzzing target binaries will be the same as other benchmarks in FuzzBench.

**Comment by sykweon** [comment]
Got it! thank you so much

**Comment by sykweon** [comment]
Sry to bother u again.
I encounter number of undefined reference errors I run `build.sh` in the docker container created after `make -f triage.mk 
This is the command:
```
$ sudo docker run -it gcr.io/fuzzbench/builders/fr_triage_driver/lcms /bin/bash
# ./build.sh
```
These are the errors I'm getting
```
+ clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -stdlib=libc++ /src/cms_transform_fuzzer.cc -I include/ src/.libs/liblcms2.a /usr/lib/FRFuzzingDriver.a -o /out/cms_transform_fuzzer
/usr/lib/FRFuzzingDriver.a(FRFuzzingEngine.o): In function `ExecuteFilesOnyByOne':
/src/FRFuzzingEngine.c:22: undefined reference to `__ubsan_handle_type_mismatch_v1'
/src/FRFuzzingEngine.c:22: undefined reference to `__asan_report_load8'
/src/FRFuzzingEngine.c:22: undefined reference to `__asan_report_load8'
/src/FRFuzzingEngine.c:30: undefined reference to `__asan_report_load8'
/usr/lib/FRFuzzingDriver.a(FRFuzzingEngine.o): In function `asan.module_ctor':
FRFuzzingEngine.c:(.text.asan.module_ctor+0x5): undefined reference to `__asan_init'
FRFuzzingEngine.c:(.text.asan.module_ctor+0xa): undefined reference to `__asan_version_mismatch_check_v8'
FRFuzzingEngine.c:(.text.asan.module_ctor+0x19): undefined reference to `__asan_register_globals'
/usr/lib/FRFuzzingDriver.a(FRFuzzingEngine.o): In function `asan.module_dtor':
FRFuzzingEngine.c:(.text.asan.module_dtor+0xf): undefined reference to `__asan_unregister_globals'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

One thing is that `/src/FRFuzzingEngine.c` does not exist. Am I supposed to copy the file into the docker container? However, the same error appears when I try to run outside of the docker container and when the FRFuzzingEngine.c file exists.
How can I fix this error?

**Comment by SlaterLatiao** [comment]
`FRFuzzingEngine.c` is the source file of `FRFuzzingEngine.o`, which is packed into `/usr/lib/FRFuzzingDriver.a`. The `build.sh` script is [automatically run when building the image](https://github.com/google/fuzzbench/blob/master/fuzzers/utils.py#L81).

As you already have `gcr.io/fuzzbench/builders/fr_triage_driver/lcms` successfully built, you are good to run the triage scripts. As mentioned, 

> The triage script will automatically [copy the triage binary to workDir](https://github.com/UTD-FAST-Lab/RevBugBench/blob/main/triage/setup/triage_bin.py#L27).
