### ISSUE TITLE
triage analysis outputs keyerror

### ISSUE THREAD

**Issue by sykweon** [SlaterLatiao/RevBugBench#21]
Hi, I'm trying to output triage result, and it shows KeyError for `libxml2_xml`, `libxml2_reader`, and `usrsctp`.

```
$ PYTHONPATH=. python3 main.py -c config.ini -r
Traceback (most recent call last):
  File "/home/sk4865/proj/revbugbench/RevBugBench/triage/main.py", line 69, in <module>
    exit(main())
  File "/home/sk4865/proj/revbugbench/RevBugBench/triage/main.py", line 63, in main
    coverage_table(helper)
  File "/home/sk4865/proj/revbugbench/RevBugBench/triage/analysis/coverage_table.py", line 64, in coverage_table
    trial_cov = trial_coverage(benchmark, fuzzer, helper)
  File "/home/sk4865/proj/revbugbench/RevBugBench/triage/analysis/coverage_table.py", line 34, in trial_coverage
    summary.reaches[pattern_dict[r_id]].add(r_id)
KeyError: 59
```

I ran to see results from three other programs as well, but they worked fine.

I did manage to output some results by putting `try except`, but I would like to know how to properly avoid this error or how this will affect the outcome.

**Comment by SlaterLatiao** [comment]
This error means the fuzzer reaches an injected bug that is not found in the `dda.json` file. A mismatch is not expected here because the bugs are injected by FixReverter based on `dda.json`. 

Possible causes are
1.  A wrong `dda.json` was uploaded to this repo.
2.  The triage scripts reads a wrong `dda.json`. Possibly the `dda.json` from a different benchmark program.

Can you provide the benchmark program of the attached error message so that I can further triage?

**Comment by sykweon** [comment]
I checked both, and both the file and path are referring to the correct `dda.json` file. The benchmark program having this error is `libxml2_xml` and `libxml2_reader` and the error msg is this:

```
Traceback (most recent call last):
  File "/Revbugbench/triage/main.py", line 69, in <module>
    exit(main())
  File "/Revbugbench/triage/main.py", line 63, in main
    coverage_table(helper)
  File "/Revbugbench/triage/analysis/coverage_table.py", line 64, in coverage_table
    trial_cov = trial_coverage(benchmark, fuzzer, helper)                                                        
  File "/Revbugbench/triage/analysis/coverage_table.py", line 34, in trial_coverage                                                                                                                 
    summary.reaches[pattern_dict[r_id]].add(r_id)
KeyError: 42
```

**Comment by SlaterLatiao** [comment]
`libxml2_xml` and `libxml2_reader` are 2 different benchmarks. The [dda.json](https://github.com/UTD-FAST-Lab/RevBugBench/blob/main/ddas/libxml2_xml/dda.json) for `libxml2_xml` has the index 42, and the [dda.json](https://github.com/UTD-FAST-Lab/RevBugBench/blob/main/ddas/libxml2_reader/dda.json) for `libxml2_reader` does not.  Can you help me confirm this error (KeyError: 42) happens on both benchmarks?

**Comment by sykweon** [comment]
KeyError: 42 only occurs in `libxml2_xml`. `libxml2_reader` outputs KeyError: 25

**Comment by SlaterLatiao** [comment]
Oh actually the [dda.json](https://github.com/UTD-FAST-Lab/RevBugBench/blob/main/ddas/libxml2_xml/dda.json) for libxml2_xml does not have index 42. So the dda files for these 2 benchmarks are the wrong versions. I'll fix in a PR.

**Comment by SlaterLatiao** [comment]
Unfortunately the dda files that generate the benchmarks of `libxml2_xml` and `libxml2_reader` have been deleted. So instead, I updated the benchmark configurations based on the current dda files. You'll need to rebuild their triage binaries  in order for the triage scripts to work (you don't need to rerun the fuzzing).

The cause behind is that, although FixReverter generates same injected bugs every time, it numbers them differently. So different runs of FixReverter generates different dda files and they must be matched in order for the triage to work. We'll fix that in the future.

**Comment by sykweon** [comment]
Thank you so much! I also found there's KeyError: 115 for usrsctp. Would you update this benchmark as well, please?

**Comment by SlaterLatiao** [comment]
Thank you for reporting back! I updated usrsctp with [PR#23](https://github.com/UTD-FAST-Lab/RevBugBench/pull/23).
