### ISSUE TITLE
Missing dda.json

### ISSUE THREAD

**Issue by spencerwuwu** [SlaterLatiao/RevBugBench#5]
Hello,

I was trying out your work, but encountered `FileNotFoundError: [Errno 2] No such file or directory: ..../dda_store/binutils-fuzz_cxxfilt/dda.json'` when running triage.

Specifically, I ran the revbugbench-patched fuzzbench. Then I build the required docker image of `fr_triage_driver` found in this repo. After that, I set up `triage/config.ini` and `cd triage; python main.py -s -r -t`. 

Do you know what is the cause of this issue?

**Comment by SlaterLatiao** [comment]
The dda.json files are the data dependence analysis results generated by FixReverter. I'll push a patch to provide them.

**Comment by SlaterLatiao** [comment]
Please manually place the corresponding dda.json file on [path/to/workDir]/dda_store/[benchmark]/dda.json. I'll update the scripts and Readme to make this process easier in the near future. 
Some of the instructions in the Readme is being updated and may not work any more. Please let me know if you have any other issue using RevBugBench :).

**Comment by spencerwuwu** [comment]
Thank you for the quick response! Seems to be working now.
