### ISSUE TITLE
ModuleNotFoundError: No module named 'google.cloud.logging.handlers.handlers'

### ISSUE THREAD

**Issue by 18Song** [SlaterLatiao/RevBugBench#7]
when I execute run_experiment.py, this problem comes out. Besides, it shows
"No matching distribution found for google.cloud.logging.handlers.handlers"
when I try “pip install google.cloud.logging.handlers.handlers”.
So, how can I get this module?

**Comment by SlaterLatiao** [comment]
Hi, can you paste the call stack here?

**Comment by 18Song** [comment]
I put "traceback.print_stack()" in front of "from google.cloud.logging.handlers.handlers import CloudLoggingHandler",
and I got this.

![call_stack](https://user-images.githubusercontent.com/73453430/212517482-1f3b713e-9d3d-4d8c-ae48-b52ddf06113a.png)

**Comment by SlaterLatiao** [comment]
Which commit did you run the scripts with? There has been massive rewriting on the scripts and `run_experiment.py` has been removed. The ReadMe file is still pointing to it, which will be updated soon.

**Comment by SlaterLatiao** [comment]
The `run_experiment.py` script you ran is from FuzzBench. Have you followed these instructions https://google.github.io/fuzzbench/getting-started/prerequisites/ to set up FuzzBench?

**Comment by 18Song** [comment]
> The `run_experiment.py` script you ran is from FuzzBench. Have you followed these instructions https://google.github.io/fuzzbench/getting-started/prerequisites/ to set up FuzzBench?

I suppose it is the problem of python version.It needs 3.10,but mine is only 3.8.I'll try it later then.
By the way, I'm reproducing your paper's experiment and here are my steps.
![image](https://user-images.githubusercontent.com/73453430/212673172-4645fd02-d1e0-4791-ae84-abf45a19da4a.png)
I'm so sorry to bother you for asking if these steps are right  because I  have encountered new problems.

**Comment by SlaterLatiao** [comment]
There have been massive rewriting on the scripts and the Readme file was out-dated. Please follow the updated Readme I pushed just now. There may be some issues on the `fr_triage_driver` part that weren't covered. Please let me know if you encounter any further problems.

Regarding the instructions you pointed out, I think they still work with recent updates. Can you open a new issue and describe your problem?

**Comment by 18Song** [comment]
ok, I'll ask you later.Thank you for your reply.
